### ISSUE TITLE
void return type

### ISSUE THREAD

**Issue by JonahSdg** [usulix/laravel-netsuite#10]
Getting this error

Return value of Usulix\NetSuite\Providers\NetSuiteServiceProvider::register() must be an instance of Usulix\NetSuite\Providers\void, none

Adding :void to the functions makes this incompatible for PHP versions < 7.1

**Comment by wattsie** [comment]
Hi, sorry that was my fault, I have not used any version less than 7.3 for over a year now.
Would you like to submit a patch, else I will update and submit update tomorrow?
Many thanks.
Cheers.

**Comment by wattsie** [comment]
I feel back I messed it up for you, so I just submitted a patch.
Please let me know if you see any other issues.

**Comment by JonahSdg** [comment]
Ok thank you. Sorry I was trying to submit my patch, but I am fairly new to this github setup, so it was taking a while.

**Comment by wattsie** [comment]
No problems, I found I had type hinting automatically added to several functions.
These are all addressed within the PR I just submitted.
Cheers.

**Comment by JonahSdg** [comment]
Thanks! I really appreciate it

**Comment by usulix** [comment]
Merged this in. Thanks @wattsie
