### ISSUE TITLE
Backwards compatibility of env configurations for 'host'

### ISSUE THREAD

**Issue by JonahSdg** [usulix/laravel-netsuite#13]
Previously, during the construction of the configurations, env variables

NETSUITE_WEBSERVICES_HOST
and
NETSUITE_RESTLET_HOST

were supported.

Now it seems like only 1 env variable is supported

NETSUITE_HOST

**Comment by usulix** [comment]
Hi @JonahSdg 

So, you do you have both webservices endpoints and restlets set up in Netsuite (come to think of it, I think we do as well)?

In that case, I can see how we need both env variables.

Let me know if that is the case and I will work on restoring both options.

**Comment by wattsie** [comment]
Hi,
  Just curious what is your use case is for both WS and Restlets at the same time?

  Also, as PSR-4 autoload is only setup for a single host, we would need to register both WS and Rest.
  With the new datacenter specific URLs, we could actually simplify even more, as the URLs are all in the form of:
  SuiteTalk (SOAP and REST web services) 
            https://#######.suitetalk.api.netsuite.com
  RESTlets 
            https://#######.restlets.api.netsuite.com 

  With sandboxed accounts being
            https://#######-sb1.suitetalk.api.netsuite.com 
            https://#######-sb1.restlets.api.netsuite.com 

  I can submit a patch shortly if you like.

Cheers.

**Comment by usulix** [comment]
Thanks @wattsie, if you have the time.

**Comment by usulix** [comment]
Thanks again @wattsie. Changes merged.

**Comment by JonahSdg** [comment]
Thanks so much guys!
