### ISSUE TITLE
Patch to ConfigService.php

### ISSUE THREAD

**Issue by wattsie** [usulix/laravel-netsuite#16]
Hi,
Found an issue in src/Services/ConfigService.php

There is a double $ in the return statement for "getWebservicesConfig".

I can submit a patch my tomorrow unless you can patch and push new v1.0.1

Many thanks.

**Comment by JonahSdg** [comment]
I just submitted a pull request/patch for this.

**Comment by usulix** [comment]
I did a direct edit. Thanks @JonahSdg and @wattsie

**Comment by wattsie** [comment]
@usulix I see there is one last $$ in the getRestletConfig() return. Line #61.

Thanks for the updates. 

PS: once done, could you please push v1.0.2 if possible.

Cheers.

**Comment by usulix** [comment]
Done.

Thanks
