### ISSUE TITLE
Getting Laravel 5.6.* and Netsuite working

### ISSUE THREAD

**Issue by wattsie** [usulix/laravel-netsuite#2]
Hi,
  Started a brand new app, fresh install of Laravel 5.6, added the usulinx/laravel-netsuite via composer, then edited "config/app.php".

  As soon as the "NetSuiteServiceProvider" line was added, if you try to use artisan, ie. "php artisan package:discover" it throws errors.

  The "getMonolog()" call does not appear to be available...

  Any ideas/suggestions to get it working?

>$$ php artisan package:discover 
> 
>    Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Monolog\Logger::getMonolog()
> 
>   at /wattsie/vendor/laravel/framework/src/Illuminate/Log/Logger.php:276
>     272|      * @return mixed
>     273|      */
>     274|     public function __call($method, $parameters)
>     275|     {
>   &gt; 276|         return $this->logger->{$method}(...$parameters);
>     277|     }
>     278| }
>     279| 
> 
>   Exception trace:
> 
>   1   Illuminate\Log\Logger::__call("getMonolog", [])
>       /wattsie/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:602
> 
>   2   Illuminate\Log\LogManager::__call("getMonolog", [])
>       /wattsie/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
>

**Comment by wattsie** [comment]
FYI: I have been able to get it working by changing the following in "NetSuiteServiceProvider.php" and "NetSuiteApiProvider.php":

> $this->logger = \Log::getMonolog();

to 

> $this->logger = new \Monolog\Logger('name');

Ill leave it to you to decide the best "name" to use for the logging *smiles*

Cheers.

**Comment by usulix** [comment]
thanks @wattsie I will try to get this updated soon

**Comment by usulix** [comment]
@wattsie , I was unable to duplicate this issue. Do you perhaps have debugbar installed as well or some of the other ie (BugSnag) issue that show up as related to this ?

**Comment by wattsie** [comment]
You have already fixed this issue, as per the pull requests some 27 days ago.

So all is good.

Cheers.
