### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by wattsie** [usulix/laravel-netsuite#8]
Hi,
  Just wondering if you can do a version bump, and support the newer versions from Ryan Winchester's library.

  ie. "ryanwinchester/netsuite-php": "v2018.2.0"

  Also, any chance of a semver update so instead of using "dev-master" one can use "^1.0" etc.
  Reason being, when running a "composer validate", this is the only package I have alerts for... "unbound version constraints (dev-master) should be avoided"

  Can do a pull request if you dont have time.

  Many thanks in advance.

  PS: this package helps me greatly. Please keep it up and updated.

Cheers.

**Comment by usulix** [comment]
Hi Wattsie.

I have not looked at this one in a while as we sorta moved away from the need for it at my current position... but, I appreciate the feedback and will definitely bump the netsuite-php dependency and move to a semantic versioning... might take a day or two.

**Comment by wattsie** [comment]
Thanks mate.
Would be nice to bump up to a whole version release.
Happy to help where possible.
Cheers.

**Comment by wattsie** [comment]
Heya, just wondering how you are going?
Would you like me to do a PR to update?
Many thanks.

**Comment by usulix** [comment]
Hi wattsie.

I would welcome a PR. I have had trouble getting set back up for netsuite access. I let my credentials expire and do not have admin access to refresh them.

**Comment by wattsie** [comment]
This can be close when time permits.
Cheers.

**Comment by usulix** [comment]
completed
